export const CATEGORIES = [
  { id: 'history', name: 'History', emoji: '🏛️' },
  { id: 'crime', name: 'Crime', emoji: '🔍' },
  { id: 'tech', name: 'Tech', emoji: '💻' },
  { id: 'horror', name: 'Horror', emoji: '👻' },
  { id: 'kids_stories', name: 'Kids Stories', emoji: '📚' },
  { id: 'fitness', name: 'Fitness', emoji: '🏋️' },
  { id: 'science', name: 'Science', emoji: '🔬' },
  { id: 'nature', name: 'Nature', emoji: '🌿' },
  { id: 'space', name: 'Space', emoji: '🚀' },
  { id: 'mystery', name: 'Mystery', emoji: '❓' },
  { id: 'biography', name: 'Biography', emoji: '👤' },
  { id: 'mythology', name: 'Mythology', emoji: '⚡' },
  { id: 'philosophy', name: 'Philosophy', emoji: '💭' },
  { id: 'food', name: 'Food', emoji: '🍳' },
  { id: 'travel', name: 'Travel', emoji: '✈️' },
  { id: 'sports', name: 'Sports', emoji: '🏆' },
  { id: 'business', name: 'Business', emoji: '💼' },
  { id: 'self_improvement', name: 'Self Improvement', emoji: '🎯' },
];

export const SUBJECTS = {
  history: ['Ancient Egypt', 'Mohenjo-Daro', 'World War II', 'Roman Empire', 'Industrial Revolution', 'Cold War', 'Renaissance', 'Silk Road', 'Viking Age', 'French Revolution', 'Medieval Europe', 'The Great Depression'],
  crime: ['Unsolved Mysteries', 'Serial Killers', 'Famous Heists', 'Cybercrime', 'Mafia History', 'Forensic Science', 'Prison Breaks', 'Cult Stories', 'Infamous Trials', 'Organized Crime'],
  tech: ['AI & Machine Learning', 'Space Technology', 'Smartphones', 'Cybersecurity', 'Cryptocurrency', 'Robotics', 'Electric Vehicles', 'Internet History', 'Video Games', 'Social Media'],
  horror: ['Paranormal Stories', 'Creepypasta', 'Urban Legends', 'Ghost Stories', 'Haunted Places', 'Cryptids', 'Demonic Possession', 'Supernatural', 'Serial Killer Folklore'],
  kids_stories: ['Fairy Tales', "Aesop's Fables", 'Animal Stories', 'Moral Stories', 'Bedtime Stories', 'Mythological Tales', 'Folk Tales', 'Adventure Stories', 'Friendship Stories'],
  fitness: ['Weight Training', 'Cardio', 'Yoga', 'Nutrition', 'Bodybuilding', 'Calisthenics', 'Marathon Training', 'HIIT', 'Recovery & Stretching', 'Sports Science'],
  science: ['Physics', 'Chemistry', 'Biology', 'Astronomy', 'Genetics', 'Climate Change', 'Neuroscience', 'Evolution', 'Quantum Mechanics', 'Dinosaurs'],
  nature: ['Rainforests', 'Oceans', 'Deserts', 'Endangered Species', 'Animal Behavior', 'National Parks', 'Weather', 'Natural Disasters', 'Migration'],
  space: ['Solar System', 'Black Holes', 'Mars Colonization', 'Space Missions', 'Exoplanets', 'Galaxies', 'Asteroids', 'Big Bang', 'Space Stations'],
  mystery: ['Bermuda Triangle', 'Atlantis', 'Loch Ness', 'Bigfoot', 'Zodiac Killer', 'Area 51', 'Lost Cities', 'Crop Circles', 'Alcatraz', 'Jack the Ripper'],
  biography: ['Albert Einstein', 'Nikola Tesla', 'Leonardo da Vinci', 'Cleopatra', 'Shakespeare', 'Napoleon', 'Marie Curie', 'Gandhi', 'Steve Jobs'],
  mythology: ['Greek Gods', 'Norse Mythology', 'Egyptian Gods', 'Hindu Epics', 'Japanese Folklore', 'Celtic Myths', 'Aztec Legends'],
  philosophy: ['Stoicism', 'Existentialism', 'Eastern Philosophy', 'Ethics', 'Plato', 'Nietzsche', 'Socrates', 'Critical Thinking'],
  food: ['World Cuisines', 'Cooking Techniques', 'Street Food', 'Desserts', 'Food History', 'Molecular Gastronomy', 'Barbecue', 'Baking'],
  travel: ['Hidden Gems', 'Budget Travel', 'Solo Travel', 'Road Trips', 'Island Getaways', 'Mountain Treks', 'Cultural Immersion', 'Adventure'],
  sports: ['Olympics', 'Football/Soccer', 'Basketball', 'Combat Sports', 'Extreme Sports', 'World Records', 'Sports History', 'Esports'],
  business: ['Startups', 'Marketing', 'Investing', 'Entrepreneurship', 'Stock Market', 'Real Estate', 'E-commerce', 'Leadership'],
  self_improvement: ['Productivity', 'Habit Building', 'Mindfulness', 'Time Management', 'Public Speaking', 'Goal Setting', 'Stoicism'],
};
