export const AI_STYLES = [
  { id: 'none', name: 'Default', icon: '🎨', desc: 'Base model only' },
  { id: 'cozyfelt', name: 'CozyFelt', icon: '🧶', desc: 'Soft felt-textured cozy aesthetic' },
  { id: 'fantasy_painterly', name: 'Fantasy Painterly', icon: '🖌️', desc: 'Rich oil-paint fantasy scenes' },
  { id: 'paper_cut_out_style', name: 'Paper Cut Out', icon: '✂️', desc: 'Layered paper cutout art' },
  { id: 'fantasy_anime', name: 'Fantasy Anime', icon: '🌸', desc: 'Anime-style fantasy worlds' },
  { id: 'cinematic_sci_fi_cyberpunk', name: 'Cyberpunk', icon: '🌃', desc: 'Neon-lit sci-fi dystopia' },
  { id: 'fantasy_realism', name: 'Fantasy Realism', icon: '🗡️', desc: 'Realistic fantasy worlds' },
  { id: 'fantasy_puppet_style', name: 'Puppet', icon: '🎭', desc: 'Stop-motion puppet aesthetic' },
  { id: 'wild_west', name: 'Wild West', icon: '🤠', desc: 'Frontier western style' },
  { id: 'post_apocalyptic', name: 'Post Apocalyptic', icon: '☢️', desc: 'Wasteland, decay, ruin' },
  { id: 'claymation', name: 'Claymation', icon: '🏺', desc: 'Plasticine clay characters' },
  { id: 'pixar_toon', name: 'Pixar Toon', icon: '🎬', desc: '3D animated feature look' },
  { id: 'ghibli', name: 'Ghibli', icon: '🌳', desc: 'Studio Ghibli hand-painted' },
  { id: 'walgro_style', name: 'Walgro', icon: '🎨', desc: 'Bold comic illustration' },
  { id: 'goldenboy', name: 'Goldenboy', icon: '✨', desc: 'Golden cinematic tone' },
  { id: 'golden_age_comic', name: 'Golden Age Comic', icon: '📰', desc: 'Vintage 1940s comic art' },
  { id: 'anime90s', name: '90s Anime', icon: '📼', desc: 'Retro 90s cell animation style' },
];

// Mirror of backend app.config.STYLE_LORAS. Shows the user which LoRA file
// will be injected for a given style. Keep in sync with backend changes.
export const STYLE_LORA_PATHS = {
  cozyfelt: 'ltx2/CozyFelt.safetensors',
  fantasy_painterly: 'ltx2/Fantasy_Painterly.safetensors',
  paper_cut_out_style: 'ltx2/PaperCutOutStyle.safetensors',
  fantasy_anime: 'ltx2/Fantasy_Anime.safetensors',
  cinematic_sci_fi_cyberpunk: 'ltx2/Cinematic_sci-fi-cyberpunk.safetensors',
  fantasy_realism: 'ltx2/Fantasy_Realism.safetensors',
  fantasy_puppet_style: 'ltx2/FantasyPuppetStyle.safetensors',
  wild_west: 'ltx2/Wild_West.safetensors',
  post_apocalyptic: 'ltx2/Post_Apocalyptic.safetensors',
  claymation: 'ltx2/Claymation.safetensors',
  pixar_toon: 'ltx2/Pixar_Toon.safetensors',
  ghibli: 'ltx2/ghibli.safetensors',
  walgro_style: 'ltx2/walgro.safetensors',
  goldenboy: 'ltx2/goldenboy.comfy.safetensors',
  golden_age_comic: 'ltx2/GoldenAgeComic.safetensors',
  anime90s: 'ltx2/anime90s.safetensors',
};

export const VOICES = [
  { id: 'aiden', name: 'Aiden', gender: 'Male', locale: 'English' },
  { id: 'dylan', name: 'Dylan', gender: 'Male', locale: 'English' },
  { id: 'eric', name: 'Eric', gender: 'Male', locale: 'English' },
  { id: 'ono_anna', name: 'Ono Anna', gender: 'Female', locale: 'English' },
  { id: 'ryan', name: 'Ryan', gender: 'Male', locale: 'English' },
  { id: 'serena', name: 'Serena', gender: 'Female', locale: 'English' },
  { id: 'sohee', name: 'Sohee', gender: 'Female', locale: 'English' },
  { id: 'uncle_fu', name: 'Uncle Fu', gender: 'Male', locale: 'English' },
  { id: 'vivian', name: 'Vivian', gender: 'Female', locale: 'English' },
];

export const MUSIC_GENRES = [
  { id: 'ambient', name: 'Ambient', emoji: '🌊' },
  { id: 'upbeat', name: 'Upbeat', emoji: '⚡' },
  { id: 'epic', name: 'Epic', emoji: '🎬' },
  { id: 'lofi', name: 'Lo-Fi', emoji: '🎵' },
  { id: 'cinematic', name: 'Cinematic', emoji: '🎭' },
  { id: 'corporate', name: 'Corporate', emoji: '💼' },
  { id: 'none', name: 'None', emoji: '🔇' },
];

// Shared caption style presets — used by both ProjectDetail and EditVideoModal.
// textStyle drives the live preview chip. textLabel is the chip text.
// allCaps controls the All Caps toggle when the preset is selected.
export const CAPTION_PRESETS = [
  {
    id: 'tiktok_bold',
    name: 'TikTok Bold',
    font: 'Impact',
    style: 'standard',
    color: '#FFE600',
    strokeColor: '#000000',
    strokeWidth: 4,
    size: 104,
    animation: 'pop',
    allCaps: true,
    bgPreview: 'bg-[#0E1116]',
    textStyle: { fontFamily: 'Impact, Arial, sans-serif', color: '#FFE600', textShadow: '-2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000', fontSize: '14px', fontWeight: '900', letterSpacing: '0.5px' },
    textLabel: 'POP!',
  },
  {
    id: 'retro_typewriter',
    name: 'Typewriter',
    font: 'Courier-New-Bold',
    style: 'minimal',
    color: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 0,
    size: 80,
    animation: 'typewriter',
    allCaps: false,
    bgPreview: 'bg-[#18181B]',
    textStyle: { fontFamily: 'Courier New, Courier, monospace', color: '#FFFFFF', fontSize: '11px', fontWeight: 'bold' },
    textLabel: 'type_writer',
  },
  {
    id: 'dynamic_karaoke',
    name: 'Karaoke',
    font: 'Arial-Bold',
    style: 'karaoke',
    color: '#FFD700',
    strokeColor: '#000000',
    strokeWidth: 3,
    size: 92,
    animation: 'word_by_word',
    allCaps: false,
    bgPreview: 'bg-[#0E1116]',
    textStyle: { fontFamily: 'Arial, sans-serif', color: '#FFD700', textShadow: '-1.5px -1.5px 0 #000, 1.5px -1.5px 0 #000, -1.5px 1.5px 0 #000, 1.5px 1.5px 0 #000', fontSize: '12px', fontWeight: 'bold' },
    textLabel: 'Karaoke',
  },
  {
    id: 'black_box',
    name: 'Black Box',
    font: 'Helvetica-Bold',
    style: 'boxed',
    color: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 0,
    size: 88,
    animation: 'word_by_word',
    allCaps: true,
    bgPreview: 'bg-[#0E1116]',
    textStyle: { fontFamily: 'Helvetica, Arial, sans-serif', color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,0.9)', padding: '2px 5px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold' },
    textLabel: 'BOX',
  },
  {
    id: 'neon_lime',
    name: 'Neon Lime',
    font: 'Arial-Bold',
    style: 'minimal',
    color: '#C6F11D',
    strokeColor: '#000000',
    strokeWidth: 2,
    size: 96,
    animation: 'pop',
    allCaps: true,
    bgPreview: 'bg-[#050608]',
    textStyle: { fontFamily: 'Arial, sans-serif', color: '#C6F11D', textShadow: '-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000', fontSize: '13px', fontWeight: 'bold', letterSpacing: '0.5px' },
    textLabel: 'NEON',
  },
  {
    id: 'white_box',
    name: 'White Box',
    font: 'Arial-Bold',
    style: 'boxed',
    color: '#111111',
    strokeColor: '#000000',
    strokeWidth: 0,
    size: 88,
    animation: 'word_by_word',
    allCaps: true,
    bgPreview: 'bg-white',
    textStyle: { fontFamily: 'Arial, sans-serif', color: '#111', backgroundColor: 'rgba(255,255,255,0.95)', padding: '2px 6px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold' },
    textLabel: 'WHITE',
  },
  {
    id: 'fire_red',
    name: 'Fire Red',
    font: 'Impact',
    style: 'standard',
    color: '#FF3B3B',
    strokeColor: '#1A0000',
    strokeWidth: 4,
    size: 104,
    animation: 'pop',
    allCaps: true,
    bgPreview: 'bg-[#0E1116]',
    textStyle: { fontFamily: 'Impact, Arial, sans-serif', color: '#FF3B3B', textShadow: '-2px -2px 0 #1A0000, 2px -2px 0 #1A0000, -2px 2px 0 #1A0000, 2px 2px 0 #1A0000', fontSize: '14px', fontWeight: '900' },
    textLabel: 'FIRE!',
  },
  {
    id: 'ice_blue',
    name: 'Ice Blue',
    font: 'Arial-Bold',
    style: 'standard',
    color: '#5CE8FF',
    strokeColor: '#001F3F',
    strokeWidth: 3,
    size: 96,
    animation: 'pop',
    allCaps: true,
    bgPreview: 'bg-[#001F3F]',
    textStyle: { fontFamily: 'Arial, sans-serif', color: '#5CE8FF', textShadow: '-1.5px -1.5px 0 #001F3F, 1.5px 1.5px 0 #001F3F', fontSize: '13px', fontWeight: 'bold' },
    textLabel: 'ICE',
  },
  {
    id: 'highlight_yellow',
    name: 'Highlight',
    font: 'Arial-Bold',
    style: 'boxed',
    color: '#111111',
    strokeColor: '#000000',
    strokeWidth: 0,
    size: 88,
    animation: 'word_by_word',
    allCaps: false,
    bgPreview: 'bg-[#FFE600]',
    textStyle: { fontFamily: 'Arial, sans-serif', color: '#111', backgroundColor: 'rgba(255,230,0,0.95)', padding: '2px 6px', borderRadius: '3px', fontSize: '10px', fontWeight: 'bold' },
    textLabel: 'Hi-Light',
  },
];
